version: '1'

networks:
   app-tier:
      driver: bridge

name: 'crm-backend'

services:
   api:
      container_name: node-server
      env_file:
         - .env
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '8080:8080'
      depends_on:
         - postgresql
         - redis
      volumes:
         - .:/apps
      networks:
         - app-tier

   postgresql:
      container_name: postgresql
      image: 'postgres'
      restart: always
      ports:
         - '5432:5432'
      networks:
         - app-tier
      volumes:
         - /postgresql:/postgresql
      env_file:
         - .env
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}

   pgadmin:
      container_name: pgadmin
      image: 'dpage/pgadmin4'
      restart: always
      ports:
         - '5050:80'
      networks:
         - app-tier
      volumes:
         - /pgadmin:/pgadmin
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

   redis:
      container_name: redis
      image: 'redis'
      ports:
         - '6379:6379'
      networks:
         - app-tier
      volumes:
         - /redis:/redis
      env_file:
         - .env
      environment:
         REDIS_PASSWORD: ${REDIS_PASSWORD}
