networks:
   app-tier:
      driver: bridge

name: 'crm-api'

services:
   api:
      container_name: nest-app
      env_file:
         - .env
      image: quanghiep031/crm-api:1.0.0
      ports:
         - '8080:8080'
      depends_on:
         - postgres
         - pgadmin
         - redis
      volumes:
         - .:/usr/src/app
      networks:
         - app-tier

   postgres:
      container_name: postgres
      image: 'postgres'
      restart: always
      ports:
         - '5432:5432'
      networks:
         - app-tier
      volumes:
         - /postgresql:/postgresql
      env_file:
         - .env
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}

   pgadmin:
      container_name: pgadmin
      image: 'dpage/pgadmin4'
      restart: always
      ports:
         - '5050:80'
      networks:
         - app-tier
      volumes:
         - /pgadmin:/pgadmin
      env_file:
         - .env
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

   redis:
      container_name: redis
      image: 'redis'
      restart: always
      ports:
         - '6379:6379'
      networks:
         - app-tier
      volumes:
         - /redis:/redis
      env_file:
         - .env
      environment:
         REDIS_PASSWORD: ${REDIS_PASSWORD}
