name: Deploy Node.js App to VPS with Docker

on:
   push:
      branches:
         - main # Chỉ deploy khi có thay đổi trên branch `main`
   workflow_dispatch: # Cho phép chạy thủ công từ GitHub Actions

jobs:
   build:
      name: Build & Push Docker Image
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [22]

      steps:
         - uses: actions/checkout@v4
         - name: Install pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 10
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v4
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'pnpm'
         - name: Install dependencies
           run: pnpm install

         - name: Log in to Docker Hub
           run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

         - name: Build Docker image
           run: |
              docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }} .

         - name: Push Docker image to Docker Hub
           run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}

   deploy:
      name: Deploy to VPS
      runs-on: ubuntu-latest
      needs: build

      steps:
         - name: Deploy to VPS via SSH
           uses: appleboy/ssh-action@v1.2.0
           with:
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USER }}
              key: ${{ secrets.VPS_SSH_KEY }}
              script: |
                 docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}
                 docker stop ${{ secrets.APP_NAME }} || true
                 docker rm ${{ secrets.APP_NAME }} || true
                 docker run -d --name ${{ secrets.APP_NAME }} -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}
